# GET con y sin id
GET http://localhost:3080/api/v1/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1NTU5OTk3LCJleHAiOjE2ODU1NjM1OTd9.5Kh6-b0GD0YSiuGBl8QHs0haC4UICBrHpDQZ_JNL0dQ
### GET Authorization 
GET http://localhost:3080/api/v1/users/restrictedView
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1NTU5OTE3LCJleHAiOjE2ODU1NjM1MTd9.Fg_GiLGC09Gkj44S9jz6qd5EhTSv8ctaZWMSt_UdJKY"


### GET hi
GET http://localhost:3080/

### GET health
GET http://localhost:3080/health

###POST 
POST http://localhost:3080/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1NTU5OTU5LCJleHAiOjE2ODU1NjM1NTl9.aM6xlab6cGMb7lQ6M0vY18kIq_4Gi7E1Lql3284tfSo

{
    "firstName": "Carlos",
    "lastName": "Herrera",
    "birthday": "1952-12-17",
    "dni": 70042297,
    "username": "carlos_herrera@gmail.com",
    "password": "Prueba+1/",
    "country": "Colombia"
}

###POST login
POST http://localhost:3080/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "carlos_herrera@gmail.com",
    "password": "Prueba+1/"
}

###DELETE con ID unico
DELETE http://localhost:3080/api/v1/users/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1NTU5OTU5LCJleHAiOjE2ODU1NjM1NTl9.aM6xlab6cGMb7lQ6M0vY18kIq_4Gi7E1Lql3284tfSo

###PATCH con ID unico
PATCH  http://localhost:3080/api/v1/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJDYXJsb3MiLCJsYXN0TmFtZSI6IkhlcnJlcmEiLCJiaXJ0aGRheSI6IjE5NTItMTItMTcifQ.3616u9a1MQUB48vhTbjVSEm46XWi9YryPD3smrjL9V8

{
    "firstName":"Carlos Mario"
}